CREATE TABLE IF NOT EXISTS vpn_users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  os_type VARCHAR(10) NOT NULL CHECK (os_type IN ('linux', 'windows')),
  ip_address VARCHAR(15) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 